In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### Sentences
sent = [ 'the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
##Define the vocabulary size
voc_size = 10000

In [5]:
### One Hot Representation
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4028, 1552, 9563, 426],
 [4028, 1552, 9563, 9173],
 [4028, 4085, 9563, 9229],
 [3822, 649, 749, 9968, 458],
 [3822, 649, 749, 9968, 1558],
 [8017, 4028, 3505, 9563, 5263],
 [1128, 1925, 9255, 9968]]

In [6]:
## word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [10]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4028 1552 9563  426]
 [   0    0    0    0 4028 1552 9563 9173]
 [   0    0    0    0 4028 4085 9563 9229]
 [   0    0    0 3822  649  749 9968  458]
 [   0    0    0 3822  649  749 9968 1558]
 [   0    0    0 8017 4028 3505 9563 5263]
 [   0    0    0    0 1128 1925 9255 9968]]


In [11]:
## feature representation 
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\devya\Desktop\Devyani\Udemy\GenAi_with_Langchain_and_Huggingface\Project\venv\Lib\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 724ms/step


array([[[-1.55846030e-03,  3.97992767e-02,  2.03248970e-02,
          4.99790646e-02,  4.89834808e-02,  4.77915518e-02,
         -2.56053936e-02,  1.18321404e-02, -9.23080370e-03,
         -9.34433937e-03],
        [-1.55846030e-03,  3.97992767e-02,  2.03248970e-02,
          4.99790646e-02,  4.89834808e-02,  4.77915518e-02,
         -2.56053936e-02,  1.18321404e-02, -9.23080370e-03,
         -9.34433937e-03],
        [-1.55846030e-03,  3.97992767e-02,  2.03248970e-02,
          4.99790646e-02,  4.89834808e-02,  4.77915518e-02,
         -2.56053936e-02,  1.18321404e-02, -9.23080370e-03,
         -9.34433937e-03],
        [-1.55846030e-03,  3.97992767e-02,  2.03248970e-02,
          4.99790646e-02,  4.89834808e-02,  4.77915518e-02,
         -2.56053936e-02,  1.18321404e-02, -9.23080370e-03,
         -9.34433937e-03],
        [-3.60834599e-02, -4.08824570e-02,  4.90796901e-02,
         -3.57558578e-03, -3.93785946e-02,  1.34571530e-02,
         -4.16234881e-03,  3.45513262e-02,  2.151012